const gameHistory = [
    {
        "sanctioning_id": -21,
        "game_date": "2023-04-22",
        "home_team_abbrev": "PHH",
        "home_team_score": 152,
        "away_team_abbrev": "PIT",
        "away_team_score": 172,
    },
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-06",
        "home_team_abbrev": "KMRD",
        "home_team_score": 81,
        "away_team_abbrev": "TIL",
        "away_team_score": 197,
    },
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-06",
        "home_team_abbrev": "SWS",
        "home_team_score": 66,
        "away_team_abbrev": "TIL",
        "away_team_score": 250,
    },
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-06",
        "home_team_abbrev": "CTB",
        "home_team_score": 109,
        "away_team_abbrev": "SWS",
        "away_team_score": 108,
    },
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-06",
        "home_team_abbrev": "CTB",
        "home_team_score": 107,
        "away_team_abbrev": "KMRD",
        "away_team_score": 210,
    },    
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-07",
        "home_team_abbrev": "CTB",
        "home_team_score": 70,
        "away_team_abbrev": "TIL",
        "away_team_score": 279,
    },
    {
        "sanctioning_id": -20,
        "game_date": "2023-05-07",
        "home_team_abbrev": "KMRD",
        "home_team_score": 224,
        "away_team_abbrev": "SWS",
        "away_team_score": 128,
    },
    {
        "sanctioning_id": -19,
        "game_date": "2023-05-12",
        "home_team_abbrev": "TMRD",
        "home_team_score": 168,
        "away_team_abbrev": "ChCRD",
        "away_team_score": 176,
    },
    {
        "sanctioning_id": -18,
        "game_date": "2023-05-13",
        "home_team_abbrev": "ChCRD",
        "home_team_score": 148,
        "away_team_abbrev": "TMRD",
        "away_team_score": 173,
    },
//    {
//        "sanctioning_id": -18,
//        "game_date": "2023-05-13",
//        "home_team_abbrev": "RCR",
//        "home_team_score": 100,
//        "away_team_abbrev": "SLGK",
//        "away_team_score": 0,
//    },
    {
        "sanctioning_id": -18,
        "game_date": "2023-05-13",
        "home_team_abbrev": "TRD",
        "home_team_score": 66,
        "away_team_abbrev": "PIT",
        "away_team_score": 533,
    },
    {
        "sanctioning_id": -17,
        "game_date": "2023-05-14",
        "home_team_abbrev": "TRD",
        "home_team_score": 169,
        "away_team_abbrev": "CGRD",
        "away_team_score": 115,
    },
    {
        "sanctioning_id": -16,
        "game_date": "2023-05-20",
        "home_team_abbrev": "CBRD",
        "home_team_score": 353,
        "away_team_abbrev": "DMRD",
        "away_team_score": 56,
    },
    {
        "sanctioning_id": -16,
        "game_date": "2023-05-20",
        "home_team_abbrev": "CBRD",
        "home_team_score": 334,
        "away_team_abbrev": "CGRD",
        "away_team_score": 46,
    },    
    {
        "sanctioning_id": -16,
        "game_date": "2023-05-20",
        "home_team_abbrev": "CGRD",
        "home_team_score": 137,
        "away_team_abbrev": "DMRD",
        "away_team_score": 206,
    },    
    {
        "sanctioning_id": -15,
        "game_date": "2023-06-03",
        "home_team_abbrev": "CGRD",
        "home_team_score": 37,
        "away_team_abbrev": "PHH",
        "away_team_score": 208,
    },    
    {
        "sanctioning_id": -15,
        "game_date": "2023-06-03",
        "home_team_abbrev": "PHH",
        "home_team_score": 96,
        "away_team_abbrev": "TMRD",
        "away_team_score": 91,
    },    
    {
        "sanctioning_id": -15,
        "game_date": "2023-06-04",
        "home_team_abbrev": "CGRD",
        "home_team_score": 51,
        "away_team_abbrev": "TMRD",
        "away_team_score": 364,
    },    
    {
        "sanctioning_id": -14,
        "game_date": "2023-06-10",
        "home_team_abbrev": "DMRD",
        "home_team_score": 59,
        "away_team_abbrev": "RCR",
        "away_team_score": 339,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-16",
        "home_team_abbrev": "CBRD",
        "home_team_score": 113,
        "away_team_abbrev": "SDA",
        "away_team_score": 236,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-17",
        "home_team_abbrev": "DGC",
        "home_team_score": 230,
        "away_team_abbrev": "SDA",
        "away_team_score": 120,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-17",
        "home_team_abbrev": "DGC",
        "home_team_score": 113,
        "away_team_abbrev": "SLGK",
        "away_team_score": 168,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-17",
        "home_team_abbrev": "SLGK",
        "home_team_score": 284,
        "away_team_abbrev": "CBRD",
        "away_team_score": 77,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-18",
        "home_team_abbrev": "CBRD",
        "home_team_score": 55,
        "away_team_abbrev": "DGC",
        "away_team_score": 413,
    },
    {
        "sanctioning_id": -13, //Sibling Rivalry
        "game_date": "2023-06-18",
        "home_team_abbrev": "SDA",
        "home_team_score": 75,
        "away_team_abbrev": "SLGK",
        "away_team_score": 290,
    },
    {
        "sanctioning_id": -12,
        "game_date": "2023-06-24",
        "home_team_abbrev": "MRD",
        "home_team_score": 274,
        "away_team_abbrev": "TNF",
        "away_team_score": 261,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "AUA",
        "home_team_score": 135,
        "away_team_abbrev": "PIT",
        "away_team_score": 121,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "AUA",
        "home_team_score": 43,
        "away_team_abbrev": "CBB",
        "away_team_score": 173,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "CWB",
        "home_team_score": 172,
        "away_team_abbrev": "DIS",
        "away_team_score": 175,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "CWB",
        "home_team_score": 147,
        "away_team_abbrev": "CRD",
        "away_team_score": 136,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "CBB",
        "home_team_score": 124,
        "away_team_abbrev": "PIT",
        "away_team_score": 135,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-24",
        "home_team_abbrev": "DIS",
        "home_team_score": 180,
        "away_team_abbrev": "CRD",
        "away_team_score": 96,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-25",
        "home_team_abbrev": "CWB",
        "home_team_score": 232,
        "away_team_abbrev": "AUA",
        "away_team_score": 91,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-25",
        "home_team_abbrev": "CBB",
        "home_team_score": 102,
        "away_team_abbrev": "DIS",
        "away_team_score": 142,
    },
    {
        "sanctioning_id": -11, //DotD
        "game_date": "2023-06-25",
        "home_team_abbrev": "PIT",
        "home_team_score": 122,
        "away_team_abbrev": "CRD",
        "away_team_score": 115,
    },    
    {
        "sanctioning_id": -10,
        "game_date": "2023-07-08",
        "home_team_abbrev": "CWB",
        "home_team_score": 386,
        "away_team_abbrev": "CGRD",
        "away_team_score": 85,
    },
    {
        "sanctioning_id": -10,
        "game_date": "2023-07-08",
        "home_team_abbrev": "CWB",
        "home_team_score": 200,
        "away_team_abbrev": "PHH",
        "away_team_score": 147,
    },    
    {
        "sanctioning_id": -10,
        "game_date": "2023-07-09",
        "home_team_abbrev": "CGRD",
        "home_team_score": 72,
        "away_team_abbrev": "PHH",
        "away_team_score": 252,
    },    
    {
        "sanctioning_id": -9, //Salem Slam
        "game_date": "2023-07-15",
        "home_team_abbrev": "ChCRD",
        "home_team_score": 173,
        "away_team_abbrev": "PSOD",
        "away_team_score": 163,
    },
    {
        "sanctioning_id": -9, //Salem Slam
        "game_date": "2023-07-15",
        "home_team_abbrev": "ChCRD",
        "home_team_score": 81,
        "away_team_abbrev": "CRD",
        "away_team_score": 208,
    },
    {
        "sanctioning_id": -9, //Salem Slam
        "game_date": "2023-07-15",
        "home_team_abbrev": "CRD",
        "home_team_score": 176,
        "away_team_abbrev": "PSOD",
        "away_team_score": 175,
    },
    {
        "sanctioning_id": -8,
        "game_date": "2023-07-15",
        "home_team_abbrev": "RCR",
        "home_team_score": 145,
        "away_team_abbrev": "CBB",
        "away_team_score": 132,
    },
    {
        "sanctioning_id": -7,
        "game_date": "2023-07-22",
        "home_team_abbrev": "TIL",
        "home_team_score": 217,
        "away_team_abbrev": "TNF",
        "away_team_score": 299,
    },
    {
        "sanctioning_id": -6,
        "game_date": "2023-07-29",
        "home_team_abbrev": "CGRD",
        "home_team_score": 35,
        "away_team_abbrev": "RCR",
        "away_team_score": 313,
    },
    {
        "sanctioning_id": -5,
        "game_date": "2023-07-29",
        "home_team_abbrev": "MRD",
        "home_team_score": 300,
        "away_team_abbrev": "TNF",
        "away_team_score": 147,
    },
    {
        "sanctioning_id": -4,
        "game_date": "2023-09-09",
        "home_team_abbrev": "TIL",
        "home_team_score": 193,
        "away_team_abbrev": "KMRD",
        "away_team_score": 106,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "CWB",
        "home_team_score": 167,
        "away_team_abbrev": "RCR",
        "away_team_score": 134,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "CBB",
        "home_team_score": 154,
        "away_team_abbrev": "PHH",
        "away_team_score": 44,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "CBB",
        "home_team_score": 49,
        "away_team_abbrev": "SLGK",
        "away_team_score": 278,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "DGC",
        "home_team_score": 228,
        "away_team_abbrev": "CRD",
        "away_team_score": 118,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "DIS",
        "home_team_score": 130,
        "away_team_abbrev": "SDA",
        "away_team_score": 169,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-21",
        "home_team_abbrev": "CRD",
        "home_team_score": 201,
        "away_team_abbrev": "PIT",
        "away_team_score": 79,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "DIS",
        "home_team_score": 162,
        "away_team_abbrev": "PHH",
        "away_team_score": 92,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "CWB",
        "home_team_score": 123,
        "away_team_abbrev": "SDA",
        "away_team_score": 279,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "CWB",
        "home_team_score": 43,
        "away_team_abbrev": "SLGK",
        "away_team_score": 291,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "DGC",
        "home_team_score": 151,
        "away_team_abbrev": "SLGK",
        "away_team_score": 130,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "DGC",
        "home_team_score": 243,
        "away_team_abbrev": "SDA",
        "away_team_score": 128,
    },
    {
        "sanctioning_id": -3, //Western Hemisphere Cup
        "game_date": "2023-10-22",
        "home_team_abbrev": "PIT",
        "home_team_score": 115,
        "away_team_abbrev": "RCR",
        "away_team_score": 191,
    },
    {
        "sanctioning_id": -2, //ACE Autumn Clash
        "game_date": "2023-11-18",
        "home_team_abbrev": "DHR",
        "home_team_score": 82,
        "away_team_abbrev": "BBRD",
        "away_team_score": 256,
    },
    {
        "sanctioning_id": -2, //ACE Autumn Clash
        "game_date": "2023-11-18",
        "home_team_abbrev": "PAN",
        "home_team_score": 111,
        "away_team_abbrev": "BBRD",
        "away_team_score": 193,
    },
    {
        "sanctioning_id": -2, //ACE Autumn Clash
        "game_date": "2023-11-18",
        "home_team_abbrev": "DHR",
        "home_team_score": 103,
        "away_team_abbrev": "PAN",
        "away_team_score": 158,
    },
    {
        "sanctioning_id": -1,
        "game_date": "2023-11-25",
        "home_team_abbrev": "TIL",
        "home_team_score": 91,
        "away_team_abbrev": "MRD",
        "away_team_score": 219,
    },
]