const teamInfo = {
    "2676a": {"team_abbreviation": "AUA"}, //Austin Anarchy (A)
    "2685a": {"team_abbreviation": "CWB"}, //Carolina Wreckingballs (A)
    "2686a": {"team_abbreviation": "CBRD"}, //Casco Bay Roller Derby (A)
    "2686b": {"team_abbreviation": "CBRD(B)"}, //Casco Bay Roller Derby (B)
    "2687a": {"team_abbreviation": "CBB"}, //Chicago Bruise Brothers (A)
    "2687b": {"team_abbreviation": "CBB(B)"}, //Chicago Bruise Brothers (B)
    "2689a": {"team_abbreviation": "CGRD"}, //Cleveland Guardians Roller Derby (A)
    "2692a": {"team_abbreviation": "CTB"}, //Crash Test Brummies (A)
    "2693a": {"team_abbreviation": "DGC"}, //Denver Ground Control (A)
    "2694a": {"team_abbreviation": "DMRD"}, //Detroit Mens Roller Derby (A)
    "2696a": {"team_abbreviation": "ChCRD"}, //Chinook City Roller Derby (A)
    "2699a": {"team_abbreviation": "CRD", "distance_clause_applies": true}, //Concussion Roller Derby (A)
    "2699b": {"team_abbreviation": "CRD(B)", "distance_clause_applies": true}, //Concussion Roller Derby (B)
    "2701a": {"team_abbreviation": "MCM"}, //Magic City Misfits (A)
    "2702a": {"team_abbreviation": "MRD"}, //Manchester Roller Derby (A)
    "2702b": {"team_abbreviation": "MRD(B)"}, //Manchester Roller Derby (B)
    "2714a": {"team_abbreviation": "PAN"}, //Panam Squad (A)
    "2715a": {"team_abbreviation": "PHH"}, //Philadelphia Hooligans (A)
    "2715b": {"team_abbreviation": "PHH(B)"}, //Philadelphia Hooligans (B)
    "2717a": {"team_abbreviation": "PSOD", "distance_clause_applies": true}, //Puget Sound Outcast Derby (A)
    "2719a": {"team_abbreviation": "RCR"}, //Race City Rebels (A)
    "2723a": {"team_abbreviation": "SDA", "distance_clause_applies": true}, //San Diego Aftershocks (A)
    "2723b": {"team_abbreviation": "SDA(B)", "distance_clause_applies": true}, //San Diego Aftershocks (B)
    "2725a": {"team_abbreviation": "SWS"}, //South Wales Silures (A)
    "2727a": {"team_abbreviation": "SLGK"}, //Saint Louis Gatekeepers (A)
    "2727b": {"team_abbreviation": "SLGK(B)"}, //Saint Louis Gatekeepers (B)
    "2733a": {"team_abbreviation": "TIL"}, //The Inhuman League (A)
    "2735a": {"team_abbreviation": "TMRD"}, //Toronto Mens Roller Derby (A)
    "2737a": {"team_abbreviation": "TNF"}, //Tyne and Fear Roller Derby (A)
    "2737b": {"team_abbreviation": "TNF(B)"}, //Tyne and Fear Roller Derby (B)
    "3013a": {"team_abbreviation": "TRD"}, //Terminus Roller Derby (A)
    "13122a": {"team_abbreviation": "KMRD"}, //Kent Mens Roller Derby (A)
    "17403a": {"team_abbreviation": "PIT"}, //Pittsburgh Roller Derby (A)
    "17403b": {"team_abbreviation": "PIT(B)"}, //Pittsburgh Roller Derby (B)
    "17404a": {"team_abbreviation": "DHR"}, //D.H.R. Men's Roller Derby (A)
    "17405a": {"team_abbreviation": "FCF"}, //Flour City Roller Derby (A)
    "17908a": {"team_abbreviation": "DIS", "distance_clause_applies": true}, //Disorder (A)
    "17909a": {"team_abbreviation": "BBRD"}, //Borderland Bandits Roller Derby (A)
    "17910a": {"team_abbreviation": "NDT"}, //Nordicks de Touraine (A)
    "17911a": {"team_abbreviation": "RDT"}, //Roller Derby Toulouse (A)
    "17912a": {"team_abbreviation": "TMP"}, //Tampa Roller Derby (A)
    "17913a": {"team_abbreviation": "SDRD"}, //Southern Discomfort Roller Derby (A)
    "17914a": {"team_abbreviation": "DDD"}, //Dallas Derby Devils (A)
    "17915a": {"team_abbreviation": "RDNA"}, //Roller Derby Nantes Atlantique (A)
    "17916a": {"team_abbreviation": "ORD"}, //Orcet Roller Derby (A)
    "17917a": {"team_abbreviation": "WRD"}, //Wirral Roller Derby (A)
}