team_info = {
    "2676a": { "region": "AM", "name": "Austin Anarchy", "logo": "team-logos/austin-anarchy.jpg" }, # Austin Anarchy (A)
    "2685a": { "region": "AM", "name": "Carolina Wreckingballs" }, # Carolina Wreckingballs (A)
    "2686a": { "region": "AM", "name": "Casco Bay Not So Jolly Rogers" }, # Casco Bay Roller Derby (A)
    "2686b": { "region": "AM", "name": "Casco Bay Black Sails" }, # Casco Bay Roller Derby (B)
    "2687a": { "region": "AM", "name": "Chicago Bruise Brothers" }, # Chicago Bruise Brothers (A)
    "2687b": { "region": "AM", "name": "Chicago Step Brothers" }, # Chicago Bruise Brothers (B)
    "2689a": { "region": "AM", "name": "Cleveland Guardians" }, # Cleveland Guardians Roller Derby (A)
    "2693a": { "region": "AM", "name": "Denver Ground Control" }, # Denver Ground Control (A)
    "2694a": { "region": "AM", "name": "Detroit Riot", "logo": "team-logos/detroit-riot.jpg" }, # Detroit Mens Roller Derby (A)
    "2696a": { "region": "AM", "name": "Chinook Glenmore Reservoir Dogs" }, # Chinook City Roller Derby (A)
    "2699a": { "region": "AM", "name": "Concussion", "distance_clause_applies": True }, # Concussion Roller Derby (A)
    "2699b": { "region": "AM", "name": "Brainstorm", "distance_clause_applies": True }, # Concussion Roller Derby (B)
    "2701a": { "region": "AM", "name": "Magic City Misfits" }, # Magic City Misfits (A)
    "2706a": { "region": "AM", "name": "Wisconsin United" }, # Wisconsin United Roller Derby (A)
    "2715a": { "region": "AM", "name": "Philadelphia Hooligans" }, # Philadelphia Hooligans (A)
    "2715b": { "region": "AM", "name": "Philadelphia Shenanigans" }, # Philadelphia Hooligans (B)
    "2717a": { "region": "AM", "name": "Puget Sound Outcast", "distance_clause_applies": True }, # Puget Sound Outcast Derby (A)
    "2719a": { "region": "AM", "name": "Race City Rebels" }, # Race City Rebels (A)
    "2723a": { "region": "AM", "name": "San Diego Aftershocks", "distance_clause_applies": True }, # San Diego Aftershocks (A)
    "2723b": { "region": "AM", "name": "San Diego Tremors", "distance_clause_applies": True }, # San Diego Aftershocks (B)
    "2727a": { "region": "AM", "name": "Saint Louis Gatekeepers" }, # Saint Louis Gatekeepers (A)
    "2727b": { "region": "AM", "name": "Saint Louis B-Keepers" }, # Saint Louis Gatekeepers (B)
    "2735a": { "region": "AM", "name": "Toronto" }, # Toronto Mens Roller Derby (A)
    "3013a": { "region": "AM", "name": "Atlanta Terminus" }, # Terminus Roller Derby (A)
    "17403a": { "region": "AM", "name": "Pittsburgh Undead" }, # Pittsburgh Roller Derby (A)
    "17403b": { "region": "AM", "name": "Pittsburgh ZomBees" }, # Pittsburgh Roller Derby (B)
    "17405a": { "region": "AM", "name": "Flour City Fear", "logo": "team-logos/flour-city-fear.jpg" }, # Flour City Roller Derby (A)
    "17908a": { "region": "AM", "name": "Disorder", "distance_clause_applies": True }, # Disorder (A)
    "17912a": { "region": "AM", "name": "Tampa Death Rollers" }, # Tampa Roller Derby (A)
    "17914a": { "region": "AM", "name": "Dallas Y'allhalla" }, # Dallas Derby Devils (A)

    "2692a": { "region": "EUR", "name": "Crash Test Brummies" }, # Crash Test Brummies (A)
    "2702a": { "region": "EUR", "name": "Manchester New Wheeled Order" }, # Manchester Roller Derby (A)
    "2702b": { "region": "EUR", "name": "Manchester (B)" }, # Manchester Roller Derby (B)
    "2714a": { "region": "EUR", "name": "Panam Squad" }, # Panam Squad (A)
    "2725a": { "region": "EUR", "name": "South Wales Silures" }, # South Wales Silures (A)
    "2733a": { "region": "EUR", "name": "The Inhuman League" }, # The Inhuman League (A)
    "2737a": { "region": "EUR", "name": "Tyne and Fear" }, # Tyne and Fear Roller Derby (A)
    "2737b": { "region": "EUR", "name": "Tyne and Fear Inglorious B*stars" }, # Tyne and Fear Roller Derby (B)    
    "13122a": { "region": "EUR", "name": "Kent" }, # Kent Mens Roller Derby (A)
    "17404a": { "region": "EUR", "name": "D.H.R." }, # D.H.R. Men's Roller Derby (A)
    "17909a": { "region": "EUR", "name": "Borderland Bandits" }, # Borderland Bandits Roller Derby (A)
    "17910a": { "region": "EUR", "name": "Nordiks de Touraine Track'Ass" }, # Nordiks de Touraine (A)
    "17911a": { "region": "EUR", "name": "Toulouse Quad Guards" }, # Roller Derby Toulouse (A)
    "17913a": { "region": "EUR", "name": "Southern Discomfort" }, # Southern Discomfort Roller Derby (A)
    "17915a": { "region": "EUR", "name": "Nantes Atlantique Jules Vénères" }, # Roller Derby Nantes Atlantique (A)
    "17916a": { "region": "EUR", "name": "Orcet Wolfgang" }, # Orcet Roller Derby (A)
    "17917a": { "region": "EUR", "name": "Wirral Pack Animals" }, # Wirral Roller Derby (A)    
}