team_info = {
    "2676a": { "region": "AM", "name": "Austin Anarchy", "location":"Austin, Texas – USA", "logo": "img/austin-anarchy.jpg" }, # Austin Anarchy (A)
    "2685a": { "region": "AM", "name": "Carolina Wreckingballs", "location":"Columbia, South Carolina – USA" }, # Carolina Wreckingballs (A)
    "2686a": { "region": "AM", "name": "Casco Bay Not So Jolly Rogers", "location":"Westbrook, Maine – USA" }, # Casco Bay Roller Derby (A)
    "2686b": { "region": "AM", "name": "Casco Bay Black Sails", "location":"Westbrook, Maine – USA" }, # Casco Bay Roller Derby (B)
    "2687a": { "region": "AM", "name": "Chicago Bruise Brothers", "location":"Chicago, Illinois – USA" }, # Chicago Bruise Brothers (A)
    "2687b": { "region": "AM", "name": "Chicago Step Brothers", "location":"Chicago, Illinois – USA" }, # Chicago Bruise Brothers (B)
    "2689a": { "region": "AM", "name": "Cleveland Guardians", "location":"Cleveland Heights, Ohio – USA" }, # Cleveland Guardians Roller Derby (A)
    "2693a": { "region": "AM", "name": "Denver Ground Control", "location":"Denver, Colorado – USA" }, # Denver Ground Control (A)
    "2694a": { "region": "AM", "name": "Detroit Riot", "location":"Detroit, Michigan – USA", "logo": "img/detroit-riot.jpg" }, # Detroit Mens Roller Derby (A)
    "2696a": { "region": "AM", "name": "Chinook Glenmore Reservoir Dogs", "location":"Calgary, Alberta – CAN" }, # Chinook City Roller Derby (A)
    "2699a": { "region": "AM", "name": "Concussion", "location":"Salem, Oregon – USA", "distance_clause_applies": True }, # Concussion Roller Derby (A)
    "2699b": { "region": "AM", "name": "Brainstorm", "location":"Salem, Oregon – USA", "distance_clause_applies": True }, # Concussion Roller Derby (B)
    "2701a": { "region": "AM", "name": "Magic City Misfits", "location":"DeLand, Florida – USA" }, # Magic City Misfits (A)
    "2706a": { "region": "AM", "name": "Wisconsin United", "location":"Madison, Wisconsin – USA" }, # Wisconsin United Roller Derby (A)
    "2715a": { "region": "AM", "name": "Philadelphia Hooligans", "location":"Philadelphia, Pennsylvania – USA" }, # Philadelphia Hooligans (A)
    "2715b": { "region": "AM", "name": "Philadelphia Shenanigans", "location":"Philadelphia, Pennsylvania – USA" }, # Philadelphia Hooligans (B)
    "2717a": { "region": "AM", "name": "Puget Sound Outcast", "location":"Seattle, Washington – USA", "distance_clause_applies": True }, # Puget Sound Outcast Derby (A)
    "2719a": { "region": "AM", "name": "Race City Rebels", "location":"Indianapolis, Indiana – USA" }, # Race City Rebels (A)
    "2723a": { "region": "AM", "name": "San Diego Aftershocks", "location":"San Diego, California – USA", "distance_clause_applies": True }, # San Diego Aftershocks (A)
    "2723b": { "region": "AM", "name": "San Diego Tremors", "location":"San Diego, California – USA", "distance_clause_applies": True }, # San Diego Aftershocks (B)
    "2727a": { "region": "AM", "name": "Saint Louis Gatekeepers", "location":"St. Louis, Missouri – USA" }, # Saint Louis Gatekeepers (A)
    "2727b": { "region": "AM", "name": "Saint Louis B-Keepers", "location":"St. Louis, Missouri – USA" }, # Saint Louis Gatekeepers (B)
    "2735a": { "region": "AM", "name": "Toronto", "location":"Toronto, Ontario – CAN" }, # Toronto Mens Roller Derby (A)
    "3013a": { "region": "AM", "name": "Atlanta Terminus", "location":"Mableton, Georgia – USA" }, # Terminus Roller Derby (A)
    "17403a": { "region": "AM", "name": "Pittsburgh Undead", "location":"Pittsburgh, Pennsylvania – USA" }, # Pittsburgh Roller Derby (A)
    "17403b": { "region": "AM", "name": "Pittsburgh ZomBees", "location":"Pittsburgh, Pennsylvania – USA" }, # Pittsburgh Roller Derby (B)
    "17405a": { "region": "AM", "name": "Flour City Fear", "location":"Rochester, New York – USA", "logo": "img/flour-city-fear.jpg" }, # Flour City Roller Derby (A)
    "17908a": { "region": "AM", "name": "Disorder", "location":"Ciudad de México – MEX", "distance_clause_applies": True }, # Disorder (A)
    "17912a": { "region": "AM", "name": "Tampa Death Rollers", "location":"Tampa, Florida – USA" }, # Tampa Roller Derby (A)
    "17914a": { "region": "AM", "name": "Dallas Y'allhalla", "location":"The Colony, Texas – USA" }, # Dallas Derby Devils (A)

    "2692a": { "region": "EUR", "name": "Crash Test Brummies", "location":"Halesowen, Birmingham – UK" }, # Crash Test Brummies (A)
    "2702a": { "region": "EUR", "name": "Manchester New Wheeled Order", "location":"Manchester – UK" }, # Manchester Roller Derby (A)
    "2702b": { "region": "EUR", "name": "Manchester (B)", "location":"Manchester – UK" }, # Manchester Roller Derby (B)
    "2714a": { "region": "EUR", "name": "Panam Squad", "location":"Paris – FRA" }, # Panam Squad (A)
    "2725a": { "region": "EUR", "name": "South Wales Silures", "location":"Abercynon, South Wales – UK" }, # South Wales Silures (A)
    "2733a": { "region": "EUR", "name": "The Inhuman League", "location":"Sheffield, South Yorkshire – UK" }, # The Inhuman League (A)
    "2737a": { "region": "EUR", "name": "Tyne and Fear", "location":"Newcastle upon Tyne – UK" }, # Tyne and Fear Roller Derby (A)
    "2737b": { "region": "EUR", "name": "Tyne and Fear Inglorious B*stars", "location":"Newcastle upon Tyne – UK" }, # Tyne and Fear Roller Derby (B)    
    "13122a": { "region": "EUR", "name": "Kent", "location":"Margate, Kent – UK" }, # Kent Mens Roller Derby (A)
    "17404a": { "region": "EUR", "name": "D.H.R.", "location":"Kiel – GER" }, # D.H.R. Men's Roller Derby (A)
    "17909a": { "region": "EUR", "name": "Borderland Bandits", "location":"Stamford, Lincolnshire – UK" }, # Borderland Bandits Roller Derby (A)
    "17910a": { "region": "EUR", "name": "Tours Track'Ass", "location":"Nordiks de Touraine – FRA" }, # Nordiks de Touraine (A)
    "17911a": { "region": "EUR", "name": "Toulouse Quad Guards", "location":"Toulouse – FRA" }, # Roller Derby Toulouse (A)
    "17913a": { "region": "EUR", "name": "Southern Discomfort", "location":"London – UK" }, # Southern Discomfort Roller Derby (A)
    "17915a": { "region": "EUR", "name": "Nantes Jules Vénères", "location":"Nantes Atlantique – FRA" }, # Roller Derby Nantes Atlantique (A)
    "17916a": { "region": "EUR", "name": "Orcet Wolfgang", "location":"Romagnat – FRA" }, # Orcet Roller Derby (A)
    "17917a": { "region": "EUR", "name": "Wirral Pack Animals", "location":"Merseyside, Wirral – UK" }, # Wirral Roller Derby (A)    
}